language: python
python:
    - '3.8'



install:
    - pip install -r requirements-dev.txt

env:
    - PYTHONPATH=/home/travis/build/gcallah/OnlineDevops

script:
    - make tests

#after_success:
#    - ./deploy.sh
#
#notifications:
#  slack: devopsnyu:vAFcJBgAP2f73SqhWgb40Gjf
